name: keziacarterstudio
favicon: null
layout_spectrum: 0.920018216362223
typography_spectrum: 0.05605981149710715
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a0000'
    - '#a17c45'
    - '#c0003c'
    - '#f2ce00'
  brandStrength: 0.7540740841068327
  lightness: 0.6962595575023443
  saturation: 0.7490210570394993
  rhythmicContrast: 0.8090157594997436
purpose: []
